### PR TITLE
Add Go implementation.

### PR DESCRIPTION
**Pull request by muety**
I only ran C++ and Go. For C++ I got **48.24 M** tests per second and for Go **33.3 M**, which is about **69 %**.

### CODE REVIEW

**Comment by muety** [comment]
Actually, after replacing 64-bit floats by 32-bit floats (analogously to the CPP implementation) I got impressive **54.80**, which is even **114 %** of C++' performance.

**Comment by johnnovak** [comment]
Great! If you have time, could put this info into `results.txt`, maybe as an appendix at the end? If not that's OK too, I'll just merge it in then.

**Comment by muety** [comment]
Sure, I can do that!
I thought that it might make sense that you run the Go benchmarks yourself and add the results, given that you still have access to the same machine the previous tests were run on. That would give better comparability. 
But otherwise I will just add a little appendix note to `results.txt`, just let me know.

**Comment by johnnovak** [comment]
Yeah I don't have access to that particular machine anymore, so go ahead and I'll merge it then in.

**Comment by muety** [comment]
Done. Thanks!

**Pull request merged**
