### PR TITLE
perftest.cpp: Branchless Intersection Test

### PR DESCRIPTION
**Pull request by ghost**
Removed various if statements to make the intersection test branchless, which gave a pretty significant performance boost.

**Edit:** The generated assembly still branches towards the end. I was kind of hoping for a mask operation but oh well.

Results are better with GCC and ICC, but the performance boost from Clang doesn't seem that significant. Here's a comparison of tests done per second, in terms of millions.

| Compiler | Before | After |
|-|-|-|
| GCC 9.2.1 | 55.80 | 93.37 |
| ICC 19.0.5 | 54.76 | 93.72 |
| Clang 9.0.0 | 51.26 | 58.93 |

### CODE REVIEW

**Comment by ghost** [comment]
Ah you know what, I just read the article that references this implementation. I think it invalidates the performance comparisons with Nim and so perhaps this shouldn't get merged. I'll leave that up to you though.

**Comment by ghost** [comment]
Any thoughts on this or should I just close the PR?

**Comment by johnnovak** [comment]
Sorry, been busy. Yeah I think this performance test is fine as it is now. Thanks for the effort though :)

**Comment by ghost** [comment]
Ah okay, no worries!

**Pull request closed without merging**
